### ISSUE TITLE
Helm install of 0.15 presents blank page when ingress is behind a URL prefix

### ISSUE THREAD

**Issue by chasain** [pyroscope-io/pyroscope#1054]
I just install pyroscope for the first time today and I attempted to put it behind a URL prefix using this in the values.yaml file
```
ingress:
  enabled: true
  hosts:
    - host: localhost
      paths:
      - path: /pyroscope
        pathType: Prefix
env: 
  PYROSCOPE_BASE_URL: /pyroscope
```
But when I browsed to localhost/pyroscope I was presented with a blank page. The diagnostics panel didn't provide much insight as it was able to find everything that was requested of it
![image](https://user-images.githubusercontent.com/65615298/164563231-83db6575-4329-46f1-b8f4-7934471172ed.png)

**Comment by eh-am** [comment]
Hmm, very weird that is being able to fetch the assets correctly. Can you double check there's no error in the console. Also can you show the rendered HTML (just as a sanity check)?


Also what kind of ingress are you using?
For example, for `nginx-ingress` I got it working with the following config

```yaml
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2

  hosts:
    - host: localhost
      paths:
      - path: /pyroscope(/|$)(.*)
        pathType: Prefix
```

One common mistake I've seen is not rewriting the request to strip the `/pyroscope` bit. The thing here is that the pyroscope server still expects the requests to be made at the root (/). The only thing `PYROSCOPE_BASE_URL` does is to prepend when making requests.

**Comment by eh-am** [comment]
Also there's an [example using docker-compose here](https://github.com/pyroscope-io/pyroscope/tree/main/examples/base-url). I couldn't manage to reproduce the issue, so I think it's something with the ingress setup.

**Comment by chasain** [comment]
Thanks, I'm using traefik v2 so I needed to add a middleware and reference it
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: pyroscope-prefix
spec:
  stripPrefix:
    prefixes:
      - /pyroscope
```
```
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-pyroscope-prefix@kubernetescrd
  hosts:
    - host: localhost
      paths:
      - path: /pyroscope
        pathType: Prefix
```
That seems to have done it. Thanks for the info.
