### ISSUE TITLE
Does `ec2-sd-configs` in another account is supported now ?

### ISSUE THREAD

**Issue by futurelm** [pyroscope-io/pyroscope#1057]
in short, AWS EC2 instances are under the main AWS account, and pyroscope server is running in another AWS account. in this case, this is the scrape-configs 
```yaml
- enabled-profiles: [ cpu, mem ]
  job-name: stg-food-max-dataservice
  ec2-sd-configs:
  - region: ap-southest-1
    role_arn: arn:aws:iam::MAIN_ACCOUNT:role/ec2-readonly-role
    port: 8089
    filters:
    - name: tag:Cluster
      values:
      - stg
    - name: tag:App_Name
      values:
      - food
  relabel-configs:
  - source-labels: [__meta_ec2_private_ip]
    target-label: instance
  - source-labels: [__meta_ec2_tag_App_Name]
    target-label: app_name
````
why does it can work?  can't see error log, but can't find the target in web UI
