### ISSUE TITLE
Frontend fails to load users

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#1075]
This was raised on slack https://pyroscope.slack.com/archives/C01FJRYENPQ/p165121677003899
<img width="475" alt="image (41)" src="https://user-images.githubusercontent.com/6951209/165947602-c6875247-e64a-42b8-915f-07c7b5034abb.png">

```
auth:
  signup-default-role: ReadOnly
  internal:
   enabled: true
   signup-enabled: false
   admin:
    create: true
    name: admin
    password: admin
```
