### ISSUE TITLE
Add fgprof profiling support

### ISSUE THREAD

**Issue by exfly** [pyroscope-io/pyroscope#1851]
Add fgprof profiling support for on-cpu  as well as off-cpu profiling.

ref: https://github.com/felixge/fgprof

**Comment by korniltsev** [comment]
I believe you can already use it in pull mode

```
scrape-configs:
  - job-name: fgprof
    enabled-profiles: [fgprof_cpu]
    profiles:
      fgprof_cpu:
        path: "/debug/fgprof"
        params:
          seconds: [ "10" ]
    static-configs:
      - application: app.name.fgprof
        targets:
          - localhost:6060
```

https://flamegraph.com/share/da69b420-ac38-11ed-9038-860ef6bcd101
