### ISSUE TITLE
Helm Retention policy not working

### ISSUE THREAD

**Issue by segues** [pyroscope-io/pyroscope#1982]
We have installed the pyroscope server with the following storage retention settings, using helm in a k8s environment:
```
pyroscopeConfigs: 
  no-self-profiling: true
  retention: 72h
  exemplars-retention: 72h
```
We only have the ebpf daemonset scraping metrics from nodes.
The samples are not being deleted in the history, the server has been active for a week and the retention should be 3 days, but we continue to see that it stores the previous days.
![image](https://github.com/grafana/pyroscope/assets/104765016/4546f5d5-4a4f-4a3e-a848-3f149cec31ec)
Are we doing something wrong in our configuration? Could there be an error when the server interprets our sample retention settings?

Thanks in advance and congrats for your product :)
