### ISSUE TITLE
cant change all instance_interface_names params

### ISSUE THREAD

**Issue by youngpabl0** [pyroscope-io/pyroscope#2075]
hello guyz, really appreciate for your OSS products, i have question / found a bug:
``distributor.ring.instance_interface_names`` - phlare have this param in /api/v1/status/config but i cant change it, anywhere - cli params / yaml config params...
``query_scheduler.ring.instance_interface_names`` - same case
``overrides_exporter`` - what is this part of config from api? cause i found ``instance_interface_names`` in ``overrides_exporter.ring.instance_interface_names``
https://grafana.com/docs/phlare/latest/operators-guide/configure/reference-configuration-parameters/ i was looking here, fix my link if i get wrong please
why i'm asking? i run phlare on pure docker with network=host, i want to bind all phlare microservices to 127.0.0.1 and share public only what i want via nginx proxy
thanks a lot!

**Comment by usermakename** [comment]
hi everyone, just checking dat this issue has been lost ;)
cheers!

**Comment by youngpabl0** [comment]
hi everyone, just checking dat this issue hasn't been lost ;)
cheers!

**Comment by Rperry2174** [comment]
has not been lost -- we will get back to looking into this after we've completed the merge. Sorry for the delay!

**Comment by usermakename** [comment]
we are really appreciate all of your work guyz, take your time, dont be sorry <3

**Comment by eliteaz** [comment]
Hello guys, I have had same issue.
using pyro version `1.2.1-1`
Found a solution with such configuration:
```
api:
    base-url: "https://pyroscope.example.org"

server:
    http_listen_address: 127.0.0.1
    http_listen_port: 4040
    grpc_listen_address: 127.0.0.1
    grpc_listen_port: 9095

memberlist:
    bind_addr: [127.0.0.1]
    bind_port: 7946

frontend_worker:
    scheduler_address: "127.0.0.1"

frontend:
    scheduler_address: "127.0.0.1"
    address: 127.0.0.1

query_scheduler:
    ring:
      instance_addr: "127.0.0.1"

ingester:
    lifecycler:
      address: 127.0.0.1
```
