### ISSUE TITLE
feat: support load multi target config file 

### ISSUE THREAD

**Issue by linthan** [pyroscope-io/pyroscope#640]
background  story：
we need to scrap the profiles of many of the dynamic  target instances。 prometheus has the ability of loading configs from a directory to solve the problem.
for example:
```yaml
 scrape-configs:
  - job-name: "node"
    file_sd_configs:
      - refresh_interval: 1m
        files:
          - "/home/www/system/prometheus/conf/*.yml"
```

hope and eager for this feature to be added to the pyroscope project.
