### ISSUE TITLE
Add mutex profiling support

### ISSUE THREAD

**Issue by lizthegrey** [pyroscope-io/pyroscope#660]
https://github.com/pyroscope-io/pyroscope/blob/9e6022b95e935e81ba6a3e6c028495d271a510bf/pkg/scrape/config/config.go#L40

needs an entry for mutex profiling.

**Comment by kolesnikovae** [comment]
Default configuration only includes Go `cpu` and `mem` profiles but eventually we will extend the list. Although this part is not yet fully supported (and documented), it is possible to scrape arbitrary profiles – including `mutex`, `goroutines`, and `block`:

```yaml
scrape-configs:
- job-name: my-job
   enabled-profiles: [cpu, mem, mutex]
   profiles:
     mutex:
       path: /debug/pprof/mutex
       sample-types:
         mutex:
           units: objects
           aggregation: average
           cumulative: true
```

We will add support for all of them soon!
