### ISSUE TITLE
Trying to understand the way pyroscope profile CPU?

### ISSUE THREAD

**Issue by jobber2955** [pyroscope-io/pyroscope#855]
I know there are two ways in profiling CPU, Pull and Push, and here's my understand about them:
```Push```: Client(program itself) continuously profile and then push data to pyroscope server.
```Pull```: Pyroscope server send start profile request to client when needed, then the client start the cpu profiling and send data back to server.

If its what i think, will it mean:  Push will cost more cpu because it profile all the time, and Pull will consume cpu only when pyroscope server send profiling request?

CPU profiling could be expansive in CPU usage in some cases, and i hope i can truly understand these two method, Thanks!

**Comment by kolesnikovae** [comment]
Thank you for the question @jobber2955! I think we need to clarify this point in our docs. I'm also assuming the question concerns Go specifically.

Your understanding is correct. In practice, with default settings, push and pull methods cause almost identical overhead. But with pull mode you can configure the scrape interval and duration of the period when the Go profiler is actually active and causes the overhead.

 - `push`: [Go client](https://github.com/pyroscope-io/client) captures and sends CPU profiling data on the fixed interval of 10 seconds. Virtually, CPU profiling is enabled almost 100% of time.
 - `pull`: Pyroscope server requests the target application to enable CPU profiling for the next `duration` seconds every `scrape interval`. Both `scrape interval` and `duration` default to 10 seconds: essentially, CPU profiler is enabled almost 100% of time as well.

So when using pull mode, you can decrease the overhead by increasing the scrape interval. For example, the configuration below makes pyroscope server to activate CPU profiling for 10 seconds every minute:

```yaml
---
scrape-configs:
  - job-name: my-app
    enabled-profiles: [cpu, mem]
    scrape-interval: 1m
    static-configs:
      - application: my-application-name
        targets:
          - hostname:6060
```
