### ISSUE TITLE
.NET 6 profiling crash process

### ISSUE THREAD

**Issue by ArtemTrofimushkin** [pyroscope-io/pyroscope#888]
Hi! Thanks for great project!
We tries to use pyroscope for continuous profiling for our .net apps, running in K8S. 
Pyroscope used as side car container, for application container, both containers shares /tmp directory with .net sockets.
Everything works fine for .net core 3.1, .net 5.0, but when we started to migrate on .net 6, we observed that application container crashes every ~ 5 mins (approx)

Here is example pod manifest to reproduce this behaviour:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pyroscope-reproduce-net-6-faillure
spec:
  containers:
  - env:
    - name: COMPlus_DbgEnableMiniDump
      value: "1"
    - name: COMPlus_CreateDumpDiagnostics
      value: "1"
    image: mcr.microsoft.com/dotnet/samples:aspnetapp
    livenessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 5
    name: web
    ports:
    - containerPort: 80
      name: http
    resources:
      limits:
        cpu: "1"
        memory: 1G
      requests:
        cpu: 100m
        memory: 500M
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp
      name: dotnet-profiling
  - command:
    - /bin/sh
    - -c
    - sleep 5s; pyroscope connect --pid 1 --tag namespace=$NAMESPACE
    env:
    - name: PYROSCOPE_SERVER_ADDRESS
      value: http://pyroscope.infra-pyroscope.svc.cluster.local:4040
    - name: PYROSCOPE_SPY_NAME
      value: dotnetspy
    - name: PYROSCOPE_LOG_LEVEL
      value: debug
    - name: PYROSCOPE_APPLICATION_NAME
      value: dodo.pyro-test.web
    - name: PYROSCOPE_SAMPLE_RATE
      value: "100"
    image: pyroscope/pyroscope:0.10.2
    name: pyroscope
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
      runAsUser: 0
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp
      name: dotnet-profiling
  nodeSelector:
    kubernetes.io/os: linux
  serviceAccountName: default
  volumes:
  - name: dotnet-profiling
```
Pod uses aspnet core sample application, taken from [here](https://github.com/dotnet/dotnet-docker/tree/main/samples/aspnetapp). 
I've added COMPlus_DbgEnableMiniDump environment variables, that instructs runtime to take core dump on failure ([link](https://docs.microsoft.com/en-us/troubleshoot/developer/webapps/aspnetcore/practice-troubleshoot-linux/lab-1-3-capture-core-crash-dumps#configure-createdump-to-run-at-process-termination)). 
When application container crashed, memory dump written to /tmp folder.
